AM62AX ThreadX Example Documentation and Fixes
TexasInstruments/mcupsdk-core-k3 pull request #8
Opened 2024-12-18 23:36 UTC by jblanchard-jblopen

Add ThreadX Documentation for the ThreadX. FileX and NETX examples.
Fix build warning in filex example.

2024-12-19 08:52 UTC, shiva-ti requested changes

2024-12-19 08:52 UTC, shiva-ti commented on docs_src/docs/api_guide/components/networking/networking.md
> --\subpage NETWORKING_LWIP
we shouldn't remove any existing section. Any reason why LWIP section is removed ?

2024-12-19 08:56 UTC, shiva-ti requested changes
Documentation added for ThreadX should have a "THREADX" specific tag in addition to "SOC_AM62AX", this can be added in "ENABLED_SECTIONS" in file "docs_src/docs/api_guide/device/am62ax/includes.cfg"
This "THREADX" section can be enabled by default, but if needed we should be able disable threadX specific docs from main mcu_plus_sdk docs.

2024-12-19 13:19 UTC, jblanchard-jblopen commented
Hi,

Thank you for your feedback. We will be looking at it today.

Jonathan

On Thu, Dec 19, 2024 at 3:56 AM Shiva Tripathi ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Documentation added for ThreadX should have a "THREADX" specific tag in
> addition to "SOC_AM62AX", this can be added in "ENABLED_SECTIONS" in file
> "docs_src/docs/api_guide/device/am62ax/includes.cfg"
> This "THREADX" section can be enabled by default, but if needed we should
> be able disable threadX specific docs from main mcu_plus_sdk docs.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TexasInstruments/mcupsdk-core-k3/pull/8#pullrequestreview-2513742412>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARXNZXMOTOE3PQZIUXOU53T2GKC33AVCNFSM6AAAAABT3YLQIGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMJTG42DENBRGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-20 10:01 UTC, shiva-ti commented
Merging the PR, the comments can be addressed as additional commit later

2024-12-20 10:02 UTC, merged